preset: laravel

risky: false

enabled:
  - no_empty_comment

disabled:
  - braces
  - phpdoc_no_package
  - concat_without_spaces
  - no_blank_lines_after_class_opening
  - no_blank_lines_after_throw
  
finder:
  exclude:
    - "tests"
  name:
    - "*.php"
