@extends('web::layouts.grids.6-6')

@section('title', 'MFA Setup')
@section('page_header', 'MFA Setup')

@section('left')

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">1. Scan QR</h3>
    </div>
    <div class="panel-body">

      <p>
        Please scan the below QR code with your authenticator application.<br>
        Each time this page loads, a new token and qr code is generated.
        <img src="{!! $qr_code_url !!}" class="text-center center-block" alt="">
      </p>

    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Supported Authenticator Apps</h3>
    </div>
    <div class="panel-body">

      <ul>
        <li class="list-header list-unstyled">Preferred Apps</li>
        <li><a href="http://itunes.apple.com/us/app/google-authenticator/id388497605?mt=8">Google Authenticator for iOS</a></li>
        <li><a href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2">Google Authenticator for Android</a></li>
        <li><a href="http://apps.microsoft.com/windows/en-us/app/google-authenticator/7ea6de74-dddb-47df-92cb-40afac4d38bb">Google Authenticator (port) on Windows app store</a></li>
        <li class="list-header list-unstyled">Other Apps</li>
        <li><a href="https://www.authy.com/">Authy for iOS, Android, Chrome, OS X</a></li>
        <li><a href="https://fedorahosted.org/freeotp/">FreeOTP for iOS, Android and Peeble</a></li>
      </ul>

    </div>
  </div>

@stop

@section('right')

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">2. Confirm Code</h3>
    </div>
    <div class="panel-body">

      <p>
        Next, confirm your setup by entering a confirmation code
        generated by your authentication application.
      </p>

      <form role="form" action="{{ route('profile.mfa.setup') }}" method="post"
            class="form-horizontal">
        {{ csrf_field() }}

        <div class="box-body">

          <!-- Text input-->
          <div class="form-group">
            <label class="col-md-4 control-label" for="confirm_code">Code</label>
            <div class="col-md-6">
              <input id="confirm_code" name="confirm_code" type="text"
                     placeholder="Confirmation Code" class="form-control input-md">
            </div>
          </div>

        </div>
        <!-- /.box-body -->

        <div class="box-footer">
          <div class="form-group">
            <label class="col-md-4 control-label" for="submit"></label>
            <div class="col-md-4">
              <button id="submit" type="submit" class="btn btn-primary">Confirm Setup</button>
            </div>
          </div>
        </div>
      </form>

    </div>
  </div>

@stop
