<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta name="viewport" content="width=device-width"/>

  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <title>SeAT Email</title>


</head>

<body bgcolor="#FFFFFF">

@include('web::emails.layouts.style')

<!-- HEADER -->
<table class="head-wrap">
  <tr>
    <td></td>
    <td class="header container">

    </td>
    <td></td>
  </tr>
</table>
<!-- /HEADER -->


<!-- BODY -->
<table class="body-wrap">
  <tr>
    <td></td>
    <td class="container" bgcolor="#FFFFFF">

      <div class="content">
        <table>
          <tr>
            <td>

              @yield('content')

            </td>
          </tr>
        </table>
      </div>
      <!-- /content -->

    </td>
    <td></td>
  </tr>
</table>
<!-- /BODY -->

<!-- FOOTER -->
<table class="footer-wrap">
  <tr>
    <td></td>
    <td class="container">

      <!-- content -->
      <div class="content">
        <table>
          <tr>
            <td align="center">
              <p>
                Generated by SeAT |
                On {{ Carbon\Carbon::now() }} |
                <a href="#">
                  <unsubscribe>Unsubscribe</unsubscribe>
                </a>
              </p>
            </td>
          </tr>
        </table>
      </div>
      <!-- /content -->

    </td>
    <td></td>
  </tr>
</table>
<!-- /FOOTER -->

</body>
</html>
